tcps:
	cargo run tcp server 127.0.0.1:33333

tcpc:
	cargo run tcp client 127.0.0.1:33333

udps:
	cargo run udp server 127.0.0.1:33333

udpc:
	cargo run udp client 127.0.0.1:33333

test_tcp:
	nc 127.0.0.1 33333

test_udp:
	nc -u 127.0.0.1 33333

.PHONY: tcps tcpc udps udpc
